# Generated by Django 3.2.12 on 2022-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="time_opened",
            field=models.DateTimeField(help_text="When the thread was opened."),
        ),
    ]
