# Generated by Django 3.2.12 on 2022-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_thread_time_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='message_id',
            field=models.PositiveBigIntegerField(db_index=True, default=2, help_text='The message id.'),
            preserve_default=False,
        ),
    ]
