# Generated by Django 3.2.12 on 2022-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_threadmessage_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="specific_topic",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specifics for this thread, this is likely the exact issue (And thread name)",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="generic_topic",
            field=models.TextField(
                blank=True, default="", help_text="The generic topic for this thread."
            ),
        ),
    ]
